name: CI

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build: 

    runs-on: ubuntu-latest

    strategy:
      matrix:
        arduino-platform: ["arduino:avr"]
        include:
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:uno"
 

    steps:
    - uses: actions/checkout@v2

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.0.0

    - name: Install platform
      run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
 
    - name: Compile Sketch
      run: arduino-cli compile --fqbn ${{ matrix.fqbn }} ./tsticks
